### ISSUE TITLE
@print_table in lower window

### ISSUE THREAD

**Issue by DFillmore** [DFillmore/Z-Machine-Standard#50]
The standard describes the behaviour of @print_table in the upper window, but use of @print_table in the lower window is required (by at least Sherlock). A game can't rely on the terp being able to print a nice neat box in the lower window if the height is greater than 1. For Standard 1.0, I'd recommend explicitly stating that a height > 1 in the lower window is illegal and undefined.

**Comment by curiousdannii** [comment]
Praxix tests multiple line tables in the lower window. I haven't ever had anyone say it caused problems.

Instead of banning it, I'd suggest that it say that it prints it as regular buffered text (possibly in a proportional font), with a line break between lines, and no expectation that it will make a nice box.

**Comment by DFillmore** [comment]
I'm only banning it in because that's the expectation Infocom had, and I don't want to add new expected behavior to 1.0 terps. For a potential future 1.2, the line break at the end of each line is also my preferred response.

**Comment by DFillmore** [comment]
As near as possible, interpreters should not have to change behaviour in order to continue being 1.0 compliant. I tested the behaviour of print_table with multiple lines in the lower window in several terps a few years backs. All of them support it, but all of them gave different results.
